//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/Auth.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MceAuth")]
  public partial class MceAuth : global::ProtoBuf.IExtensible
  {
    public MceAuth() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _pass;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pass
    {
      get { return _pass; }
      set { _pass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseAuth")]
  public partial class MseAuth : global::ProtoBuf.IExtensible
  {
    public MseAuth() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private bool _succ;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succ
    {
      get { return _succ; }
      set { _succ = value; }
    }
    private long _serverTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long serverTime
    {
      get { return _serverTime; }
      set { _serverTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}