//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MceExecuteSkill.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MceExecuteSkill")]
  public partial class MceExecuteSkill : global::ProtoBuf.IExtensible
  {
    public MceExecuteSkill() {}
    
    private long _target_oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"target_oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long target_oid
    {
      get { return _target_oid; }
      set { _target_oid = value; }
    }
    private int _target_x = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"target_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target_x
    {
      get { return _target_x; }
      set { _target_x = value; }
    }
    private int _target_y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"target_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target_y
    {
      get { return _target_y; }
      set { _target_y = value; }
    }
    private int _self_x = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"self_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int self_x
    {
      get { return _self_x; }
      set { _self_x = value; }
    }
    private int _self_y = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"self_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int self_y
    {
      get { return _self_y; }
      set { _self_y = value; }
    }
    private int _skillid = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}