//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MceMove.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MceMove")]
  public partial class MceMove : global::ProtoBuf.IExtensible
  {
    public MceMove() {}
    
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _direct = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"direct", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float direct
    {
      get { return _direct; }
      set { _direct = value; }
    }
    private float _target_direct = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"target_direct", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float target_direct
    {
      get { return _target_direct; }
      set { _target_direct = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _target_speed = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"target_speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float target_speed
    {
      get { return _target_speed; }
      set { _target_speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}