//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MceMedalUpgrade.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MceMedalUpgrade")]
  public partial class MceMedalUpgrade : global::ProtoBuf.IExtensible
  {
    public MceMedalUpgrade() {}
    
    private uint _Medal_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Medal_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Medal_id
    {
      get { return _Medal_id; }
      set { _Medal_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}