//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MceMedalgemChange.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MceMedalgemChange")]
  public partial class MceMedalgemChange : global::ProtoBuf.IExtensible
  {
    public MceMedalgemChange() {}
    
    private uint _Medal_oid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Medal_oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Medal_oid
    {
      get { return _Medal_oid; }
      set { _Medal_oid = value; }
    }
    private uint _index = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _medalgem_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"medalgem_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int medalgem_id
    {
      get { return _medalgem_id; }
      set { _medalgem_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}