//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseApplyBuffer.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseApplyBuffer")]
  public partial class MseApplyBuffer : global::ProtoBuf.IExtensible
  {
    public MseApplyBuffer() {}
    
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private int _buf_type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buf_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buf_type
    {
      get { return _buf_type; }
      set { _buf_type = value; }
    }
    private int _buf_value = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buf_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buf_value
    {
      get { return _buf_value; }
      set { _buf_value = value; }
    }
    private int _hp_change = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hp_change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp_change
    {
      get { return _hp_change; }
      set { _hp_change = value; }
    }
    private int _hp_last = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hp_last", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp_last
    {
      get { return _hp_last; }
      set { _hp_last = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}