//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseAirWall.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseAirWall")]
  public partial class MseAirWall : global::ProtoBuf.IExtensible
  {
    public MseAirWall() {}
    
    private int _action = (int)1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _oid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private float _x1 = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x1
    {
      get { return _x1; }
      set { _x1 = value; }
    }
    private float _y1 = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y1
    {
      get { return _y1; }
      set { _y1 = value; }
    }
    private float _x2 = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"x2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x2
    {
      get { return _x2; }
      set { _x2 = value; }
    }
    private float _y2 = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"y2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y2
    {
      get { return _y2; }
      set { _y2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}