//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseBag.proto
// Note: requires additional types generated from: MItem.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseBag")]
  public partial class MseBag : global::ProtoBuf.IExtensible
  {
    public MseBag() {}
    
    private readonly global::System.Collections.Generic.List<MItem> _items = new global::System.Collections.Generic.List<MItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MItem> items
    {
      get { return _items; }
    }
  
    private MItem _equips = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MItem equips
    {
      get { return _equips; }
      set { _equips = value; }
    }
    private MItem _ships = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ships", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MItem ships
    {
      get { return _ships; }
      set { _ships = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}