//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseEquipList.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlessingValue")]
  public partial class BlessingValue : global::ProtoBuf.IExtensible
  {
    public BlessingValue() {}
    
    private int _left_time = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"left_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int left_time
    {
      get { return _left_time; }
      set { _left_time = value; }
    }
    private int _bless_value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bless_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bless_value
    {
      get { return _bless_value; }
      set { _bless_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attr")]
  public partial class Attr : global::ProtoBuf.IExtensible
  {
    public Attr() {}
    
    private int _attr = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private int _attr_num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attr_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attr_num
    {
      get { return _attr_num; }
      set { _attr_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomAttr")]
  public partial class RandomAttr : global::ProtoBuf.IExtensible
  {
    public RandomAttr() {}
    
    private int _attr = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private int _attr_num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attr_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attr_num
    {
      get { return _attr_num; }
      set { _attr_num = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _quality = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MEquipLite")]
  public partial class MEquipLite : global::ProtoBuf.IExtensible
  {
    public MEquipLite() {}
    
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private int _tid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _ship_id = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ship_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ship_id
    {
      get { return _ship_id; }
      set { _ship_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _atts = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"atts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> atts
    {
      get { return _atts; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _attv = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"attv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> attv
    {
      get { return _attv; }
    }
  
    private int _stk = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"stk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stk
    {
      get { return _stk; }
      set { _stk = value; }
    }
    private int _star_level = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"star_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star_level
    {
      get { return _star_level; }
      set { _star_level = value; }
    }
    private int _casting_level = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"casting_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int casting_level
    {
      get { return _casting_level; }
      set { _casting_level = value; }
    }
    private BlessingValue _enhance_blessing_value = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"enhance_blessing_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BlessingValue enhance_blessing_value
    {
      get { return _enhance_blessing_value; }
      set { _enhance_blessing_value = value; }
    }
    private BlessingValue _cast_blessing_value = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"cast_blessing_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BlessingValue cast_blessing_value
    {
      get { return _cast_blessing_value; }
      set { _cast_blessing_value = value; }
    }
    private readonly global::System.Collections.Generic.List<RandomAttr> _random_attr = new global::System.Collections.Generic.List<RandomAttr>();
    [global::ProtoBuf.ProtoMember(12, Name=@"random_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RandomAttr> random_attr
    {
      get { return _random_attr; }
    }
  
    private readonly global::System.Collections.Generic.List<Attr> _casting_attr = new global::System.Collections.Generic.List<Attr>();
    [global::ProtoBuf.ProtoMember(13, Name=@"casting_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Attr> casting_attr
    {
      get { return _casting_attr; }
    }
  
    private readonly global::System.Collections.Generic.List<RandomAttr> _random_attr_cur = new global::System.Collections.Generic.List<RandomAttr>();
    [global::ProtoBuf.ProtoMember(14, Name=@"random_attr_cur", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RandomAttr> random_attr_cur
    {
      get { return _random_attr_cur; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseEquipList")]
  public partial class MseEquipList : global::ProtoBuf.IExtensible
  {
    public MseEquipList() {}
    
    private readonly global::System.Collections.Generic.List<MEquipLite> _equip_list = new global::System.Collections.Generic.List<MEquipLite>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equip_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MEquipLite> equip_list
    {
      get { return _equip_list; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _del_list = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"del_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> del_list
    {
      get { return _del_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}