//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseEquipUpdateStar.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseEquipUpdateStar")]
  public partial class MseEquipUpdateStar : global::ProtoBuf.IExtensible
  {
    public MseEquipUpdateStar() {}
    
    private MseEquipUpdateStar.ErrorCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MseEquipUpdateStar.ErrorCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ok", Value=0)]
      Ok = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Failed", Value=1)]
      Failed = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoleLevelNotEnough", Value=2)]
      RoleLevelNotEnough = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ItemNotEnough", Value=3)]
      ItemNotEnough = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}