//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseMove.proto
// Note: requires additional types generated from: MceMove.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseMove")]
  public partial class MseMove : global::ProtoBuf.IExtensible
  {
    public MseMove() {}
    
    private readonly global::System.Collections.Generic.List<MceMove> _move_list = new global::System.Collections.Generic.List<MceMove>();
    [global::ProtoBuf.ProtoMember(2, Name=@"move_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MceMove> move_list
    {
      get { return _move_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}