//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseMedalgemChange.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MedalgemList")]
  public partial class MedalgemList : global::ProtoBuf.IExtensible
  {
    public MedalgemList() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _medalgem_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"medalgem_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int medalgem_id
    {
      get { return _medalgem_id; }
      set { _medalgem_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseMedalgemChange")]
  public partial class MseMedalgemChange : global::ProtoBuf.IExtensible
  {
    public MseMedalgemChange() {}
    
    private bool _succ = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"succ", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool succ
    {
      get { return _succ; }
      set { _succ = value; }
    }
    private readonly global::System.Collections.Generic.List<MedalgemList> _medalgem_list = new global::System.Collections.Generic.List<MedalgemList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"medalgem_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MedalgemList> medalgem_list
    {
      get { return _medalgem_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}