//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseMedalList.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MedalGemOnMedal")]
  public partial class MedalGemOnMedal : global::ProtoBuf.IExtensible
  {
    public MedalGemOnMedal() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _medalgem_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"medalgem_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int medalgem_id
    {
      get { return _medalgem_id; }
      set { _medalgem_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MedalAdditional")]
  public partial class MedalAdditional : global::ProtoBuf.IExtensible
  {
    public MedalAdditional() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MMedalLite")]
  public partial class MMedalLite : global::ProtoBuf.IExtensible
  {
    public MMedalLite() {}
    
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private int _medal_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"medal_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int medal_id
    {
      get { return _medal_id; }
      set { _medal_id = value; }
    }
    private readonly global::System.Collections.Generic.List<MedalGemOnMedal> _medalgem_list = new global::System.Collections.Generic.List<MedalGemOnMedal>();
    [global::ProtoBuf.ProtoMember(3, Name=@"medalgem_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MedalGemOnMedal> medalgem_list
    {
      get { return _medalgem_list; }
    }
  
    private readonly global::System.Collections.Generic.List<MedalAdditional> _additional_list = new global::System.Collections.Generic.List<MedalAdditional>();
    [global::ProtoBuf.ProtoMember(4, Name=@"additional_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MedalAdditional> additional_list
    {
      get { return _additional_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseMedalList")]
  public partial class MseMedalList : global::ProtoBuf.IExtensible
  {
    public MseMedalList() {}
    
    private readonly global::System.Collections.Generic.List<MMedalLite> _medal_list = new global::System.Collections.Generic.List<MMedalLite>();
    [global::ProtoBuf.ProtoMember(1, Name=@"medal_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MMedalLite> medal_list
    {
      get { return _medal_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}