//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseShipInfo.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MShipPart")]
  public partial class MShipPart : global::ProtoBuf.IExtensible
  {
    public MShipPart() {}
    
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _prop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"prop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> prop
    {
      get { return _prop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _value = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> value
    {
      get { return _value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseShipInfo")]
  public partial class MseShipInfo : global::ProtoBuf.IExtensible
  {
    public MseShipInfo() {}
    
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private int _tid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<MShipPart> _ship_part = new global::System.Collections.Generic.List<MShipPart>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ship_part", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MShipPart> ship_part
    {
      get { return _ship_part; }
    }
  
    private int _hp_recover = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hp_recover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp_recover
    {
      get { return _hp_recover; }
      set { _hp_recover = value; }
    }
    private int _max_power = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"max_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_power
    {
      get { return _max_power; }
      set { _max_power = value; }
    }
    private int _load = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"load", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int load
    {
      get { return _load; }
      set { _load = value; }
    }
    private int _max_speed = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"max_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_speed
    {
      get { return _max_speed; }
      set { _max_speed = value; }
    }
    private int _accelerated_speed = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"accelerated_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int accelerated_speed
    {
      get { return _accelerated_speed; }
      set { _accelerated_speed = value; }
    }
    private int _turn_radius = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"turn_radius", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int turn_radius
    {
      get { return _turn_radius; }
      set { _turn_radius = value; }
    }
    private int _max_hp = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"max_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_hp
    {
      get { return _max_hp; }
      set { _max_hp = value; }
    }
    private int _attack = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _armor = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"armor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int armor
    {
      get { return _armor; }
      set { _armor = value; }
    }
    private int _hit = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private int _dodge = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }
    private int _critical = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"critical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critical
    {
      get { return _critical; }
      set { _critical = value; }
    }
    private int _critical_resistance = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"critical_resistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critical_resistance
    {
      get { return _critical_resistance; }
      set { _critical_resistance = value; }
    }
    private int _damage_blast = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"damage_blast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damage_blast
    {
      get { return _damage_blast; }
      set { _damage_blast = value; }
    }
    private int _damage_kinetic = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"damage_kinetic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damage_kinetic
    {
      get { return _damage_kinetic; }
      set { _damage_kinetic = value; }
    }
    private int _damage_heat = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"damage_heat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damage_heat
    {
      get { return _damage_heat; }
      set { _damage_heat = value; }
    }
    private int _resistance_blast = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"resistance_blast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resistance_blast
    {
      get { return _resistance_blast; }
      set { _resistance_blast = value; }
    }
    private int _resistance_kinetic = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"resistance_kinetic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resistance_kinetic
    {
      get { return _resistance_kinetic; }
      set { _resistance_kinetic = value; }
    }
    private int _resistance_heat = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"resistance_heat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resistance_heat
    {
      get { return _resistance_heat; }
      set { _resistance_heat = value; }
    }
    private int _absolute_hp = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"absolute_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_hp
    {
      get { return _absolute_hp; }
      set { _absolute_hp = value; }
    }
    private int _absolute_attack = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"absolute_attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_attack
    {
      get { return _absolute_attack; }
      set { _absolute_attack = value; }
    }
    private int _absolute_armor = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"absolute_armor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_armor
    {
      get { return _absolute_armor; }
      set { _absolute_armor = value; }
    }
    private int _absolute_hit = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"absolute_hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_hit
    {
      get { return _absolute_hit; }
      set { _absolute_hit = value; }
    }
    private int _absolute_dodge = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"absolute_dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_dodge
    {
      get { return _absolute_dodge; }
      set { _absolute_dodge = value; }
    }
    private int _absolute_critical = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"absolute_critical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_critical
    {
      get { return _absolute_critical; }
      set { _absolute_critical = value; }
    }
    private int _absolute_critical_resistance = default(int);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"absolute_critical_resistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int absolute_critical_resistance
    {
      get { return _absolute_critical_resistance; }
      set { _absolute_critical_resistance = value; }
    }
    private int _critical_damage = default(int);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"critical_damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critical_damage
    {
      get { return _critical_damage; }
      set { _critical_damage = value; }
    }
    private int _critical_reduce = default(int);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"critical_reduce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int critical_reduce
    {
      get { return _critical_reduce; }
      set { _critical_reduce = value; }
    }
    private int _damage_amplify = default(int);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"damage_amplify", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damage_amplify
    {
      get { return _damage_amplify; }
      set { _damage_amplify = value; }
    }
    private int _damage_reduce = default(int);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"damage_reduce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damage_reduce
    {
      get { return _damage_reduce; }
      set { _damage_reduce = value; }
    }
    private int _suitid = default(int);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"suitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int suitid
    {
      get { return _suitid; }
      set { _suitid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}