//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseShipList.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MShipLite")]
  public partial class MShipLite : global::ProtoBuf.IExtensible
  {
    public MShipLite() {}
    
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private int _tid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private int _suitid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"suitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int suitid
    {
      get { return _suitid; }
      set { _suitid = value; }
    }
    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseShipList")]
  public partial class MseShipList : global::ProtoBuf.IExtensible
  {
    public MseShipList() {}
    
    private readonly global::System.Collections.Generic.List<MShipLite> _ship_list = new global::System.Collections.Generic.List<MShipLite>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ship_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MShipLite> ship_list
    {
      get { return _ship_list; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _del_list = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"del_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> del_list
    {
      get { return _del_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}