//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: src/MseUserInfo.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseUserInfo")]
  public partial class MseUserInfo : global::ProtoBuf.IExtensible
  {
    public MseUserInfo() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private long _oid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private int _tid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _head = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int head
    {
      get { return _head; }
      set { _head = value; }
    }
    private int _vipLevel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private int _speed = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private string _shipid = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private int _suit = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"suit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int suit
    {
      get { return _suit; }
      set { _suit = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _exp_max = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"exp_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp_max
    {
      get { return _exp_max; }
      set { _exp_max = value; }
    }
    private int _camp = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}