//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/SceneObjAppear.proto
namespace AppProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseSceneObjAppear")]
  public partial class MseSceneObjAppear : global::ProtoBuf.IExtensible
  {
    public MseSceneObjAppear() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private float _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _degree;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"degree", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float degree
    {
      get { return _degree; }
      set { _degree = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _degreeSpeed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"degreeSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float degreeSpeed
    {
      get { return _degreeSpeed; }
      set { _degreeSpeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MseSceneObjAppearList")]
  public partial class MseSceneObjAppearList : global::ProtoBuf.IExtensible
  {
    public MseSceneObjAppearList() {}
    
    private readonly global::System.Collections.Generic.List<MseSceneObjAppear> _sceneObjAppear = new global::System.Collections.Generic.List<MseSceneObjAppear>();
    [global::ProtoBuf.ProtoMember(1, Name=@"sceneObjAppear", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MseSceneObjAppear> sceneObjAppear
    {
      get { return _sceneObjAppear; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}